/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entidades.ModeloExamen;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;

/**
 *
 * @author Erick
 */
public class ResultadosGenerales extends javax.swing.JInternalFrame {

    private List<ModeloExamen> modelosExamenes;
    private DefineVariablesAnalisis dv;
    private List<String> opciones_respuesta_municipio;
    private List<Integer> frecuencias_op_res_municipio;
    private List<Double> puntaje_total_municipio;
    private List<Double> puntaje_promedio_municipio;
    private List<Double> porcentaje_aciertos_municipio;
    
    /**
     * Creates new form ResultadosGenerales
     */
    public ResultadosGenerales(List<ModeloExamen> modelosExamenes, JDesktopPane jDesktopPane1) {
        this.modelosExamenes = modelosExamenes;
        initComponents();
        
        dv = new DefineVariablesAnalisis(this.modelosExamenes, jDesktopPane1);
        
        realizarAnalisis();
        pintar_resultados();
        
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = this.getSize();

        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2, (desktopSize.height- jInternalFrameSize.height)/2);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel_resultados = new javax.swing.JEditorPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Resultados generales");

        panel_resultados.setEditable(false);
        panel_resultados.setContentType("text/html");
        jScrollPane1.setViewportView(panel_resultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane panel_resultados;
    // End of variables declaration//GEN-END:variables

    private void realizarAnalisis() {
        for(int i=0; i<this.modelosExamenes.size(); i++) {
            
            if(this.modelosExamenes.get(i).isPor_municipio()) {
                calcularPorMunicipio(i);
            }
            
            if(this.modelosExamenes.get(i).isPor_zona_escolar()) {
                calcularPorZonaEscolar(i);
            }
            
            if(this.modelosExamenes.get(i).isPor_escuela()) {
                calcularPorEscuela(i);
            }
            
            if(this.modelosExamenes.get(i).isPor_grupo()) {
                calcularPorGrupo(i);
            }
        }
    }

    private void calcularPorMunicipio(int indice_modelo) {                
        int indiceVar = this.modelosExamenes.get(indice_modelo).getIndiceVar(this.modelosExamenes.get(indice_modelo).getVarMunicipio());
        
        opciones_respuesta_municipio = new ArrayList<>();
        frecuencias_op_res_municipio = new ArrayList<>();
        puntaje_total_municipio = new ArrayList<>();
        puntaje_promedio_municipio = new ArrayList<>();
        porcentaje_aciertos_municipio = new ArrayList<>();
        
        for(int i=0; i<this.modelosExamenes.get(indice_modelo).getNumero_de_examinados(); i++) {            
            String respuesta;               
            double aciertos;

            respuesta = this.modelosExamenes.get(indice_modelo).getAlumnosOrdenada().get(i).getRespuesta(indiceVar);
            aciertos = this.modelosExamenes.get(indice_modelo).getAlumnosOrdenada().get(i).getAciertos();

            if( !opciones_respuesta_municipio.contains(respuesta) ) {
                opciones_respuesta_municipio.add(respuesta);
                frecuencias_op_res_municipio.add(new Integer(1));
                puntaje_total_municipio.add(new Double(aciertos));
            } else {
                int indice_respuesta = opciones_respuesta_municipio.indexOf(respuesta);

                if(indice_respuesta!=-1) {
                    int cont = frecuencias_op_res_municipio.get(indice_respuesta).intValue();
                    cont++;
                    frecuencias_op_res_municipio.set(indice_respuesta, new Integer(cont));
                    aciertos += puntaje_total_municipio.get(indice_respuesta); 
                    puntaje_total_municipio.set(indice_respuesta, new Double(aciertos));
                } else {
                    System.out.println("Algo raro esta pasando");
                }
            }
            
        }
        
        for(int i=0; i<opciones_respuesta_municipio.size(); i++) {
            double promedio = (puntaje_total_municipio.get(i).doubleValue()/frecuencias_op_res_municipio.get(i).intValue());
            puntaje_promedio_municipio.add(promedio);            
            porcentaje_aciertos_municipio.add(promedio/this.modelosExamenes.get(indice_modelo).getNumero_de_items());
            
            System.out.println(promedio);
        }
        
        this.modelosExamenes.get(indice_modelo).setOpciones_respuesta_municipio(opciones_respuesta_municipio);
        this.modelosExamenes.get(indice_modelo).setPuntaje_promedio_municipio(puntaje_promedio_municipio);
        this.modelosExamenes.get(indice_modelo).setPorcentaje_aciertos_municipio(porcentaje_aciertos_municipio);
    }

    private void calcularPorZonaEscolar(int indice_modelo) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private void calcularPorEscuela(int indice_modelo) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private void calcularPorGrupo(int indice_modelo) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
    private void pintar_resultados() {
        String out = "";
        DecimalFormat df = new DecimalFormat("0.000");
        
        for(int k=0; k<this.modelosExamenes.size(); k++) {            
        
            out = out +
                    "<table align=\"center\" width=\"400px\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">"
                    + "<caption style=\"font-weight:bold;\"> " + this.modelosExamenes.get(k).getNombreModelo() + "</caption>"
                    + "<tr>";
            
            out = out + "<td style=\"text-align:center; font-weight:bold;\">Municipio</td>";
            out = out + "<td style=\"text-align:center; font-weight:bold;\">Total</td>";
            out = out + "<td style=\"text-align:center; font-weight:bold;\">Porcentaje</td>";
            out = out + "</tr>";                                  
            
            out = out + "<tr>";            
            
            for(int j=0; j<this.modelosExamenes.get(k).getOpciones_respuesta_municipio().size(); j++) {                                             

                if(j!=0) {
                    out = out + "<tr>";
                }
                
                out = out + "<td style=\"text-align:center;\">" + this.modelosExamenes.get(k).getOpciones_respuesta_municipio().get(j) + " </td>";
                out = out + "<td style=\"text-align:center;\">" + df.format(this.modelosExamenes.get(k).getPuntaje_promedio_municipio().get(j).doubleValue()) + "</td>";
                out = out + "<td style=\"text-align:center;\">" + df.format(this.modelosExamenes.get(k).getPorcentaje_aciertos_municipio().get(j).doubleValue()*100) + "%</td>";
                out = out + "</tr>";                                        
            }
                        

            out = out + "</table>";
            out = out + "<br /><br />";
            
        }
        
        /*for(int k=0; k<this.modelosExamenes.size(); k++) {            
                        
            out = out +
                    "<table align=\"center\" width=\"400px\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">"
                    + "<caption style=\"text-align:center; font-weight:bold;\"> " + this.modelosExamenes.get(k).getNombreModelo() + "</caption>";
            
            for(int i=0; i<this.modelosExamenes.get(k).getCaract_graficas().size(); i++) {                                
                out = out + "<tr>"
                        +  "<td style=\"text-align:center; border:0;\">&nbsp;</td>";            

                out = out + "</tr>";            
                
                out = out + "<tr>";
                out = out + "<td style=\"text-align:center; border:0;\">";
                
                String nombreArchivo = "\"file:temp/caract/" + this.modelosExamenes.get(k).getNombreModelo() + "/" + (this.modelosExamenes.get(k).getCaract_graficas().get(i).getTitle().getText()) + ".PNG\"";                                
                
                out = out + "<img src=" + nombreArchivo + " width=\"400\" height=\"260\" border=\"0\">";
                out = out + "</td>";
                out = out + "</tr>";            
                
                out = out + "<tr>";
                out = out + "<td style=\"text-align:center; border:0;\">";
                out = out + "&nbsp;";
                out = out + "</td>";
                out = out + "</tr>";  
                
                out = out + "<tr>";
                out = out + "<td style=\"text-align:center; border:0;\">";
                out = out + "&nbsp;";
                out = out + "</td>";
                out = out + "</tr>"; 
            }        

            out = out + "</table>";
            out = out + "<br /> <br />";
        }*/
        
        this.panel_resultados.setText(out); 
    }
}
